### ISSUE TITLE
UML Class Diayagram

### ISSUE THREAD

**Issue by SemihAdiguzel** [SemihAdiguzel/BBM487-20142-9#2]
Domain analizi yaparak, bu alanla ilgili class’ları ve ilişkileri UML Class Diyagram kullanarak gösteriniz. Aynı diyagram üzerinde veri gereksinimlerini classların attribute’ları olarak belirtiniz.

**Comment by ErenNarin** [comment]
![classdiagram](https://cloud.githubusercontent.com/assets/11226220/6585915/2d17fc74-c77e-11e4-92ff-c8d76b32cefb.jpg)
Project's Class Diagram
