### ISSUE TITLE
UML use case diyagramı 

### ISSUE THREAD

**Issue by SemihAdiguzel** [SemihAdiguzel/BBM487-20142-9#3]
Sistem temel fonksiyonları UML use case diyagramı çizerek gösteriniz. Her bir use case’i bir kaç cümle ile anlatınız.

**Comment by ghost** [comment]
![use-case](https://cloud.githubusercontent.com/assets/1101682/6586173/2969fdc8-c780-11e4-9fcd-021607c05fed.png)
UML use case diagramı

**Comment by ghost** [comment]
UML use case diagramı özellikleri :
1.Öğrenci önceden kendisine tanımlanan yetkiyle sistemi kullanabilir.Öğrenci, öğrenci
numarası ve şifre ile sisteme giriş yapar.
2.Öğrenci sistemde kullandığı e-posta adresini değiştirebilir.Öğrenci kendine ait yeni bir email
adresini girip “güncelle” tuşuna basınca, yeni emalini sisteme tanıtmış olur.
3.Öğrenci kişisel bilgilerini ve aktif olan güz ya da bahar dönemi için eğitim bilgilerini
görüntüleyebilir.Öğrenci kendisine ait olan numara , ad , soyad , fakülte , bölüm ve bölüme
giriş tipi , yılı , durumu , kimlik bilgileri , adresi , telefonu, e-posta adresi ; aktif dönem için yılı ,
dönemi , program kaydı , ekle sil durumu ve danışman bilgilerini görüntüler.
4.Öğrenci, öğrenim gördüğü tüm dönemlerdeki not bilgilerine bu ekran sayesinde
ulaşır.Öğrenci, dönem seçim ekranında iken karne ayrıntılarına ulaşmak istediği bir dönemi
seçer ve “Tamam” seçimini yapar.Sistem; öğrenciye; ad, soyad, öğrenci no, fakülte, bölüm ve
danışman bilgileri ile seçtiği dönemde almış olduğu tüm dersleri gösterir. Bu gösterim; ders
kodu, ders adı, şube ve kredi bilgilerine ek olarak; genel not ve/veya bütünleme notu bilgilerini
de içerir.
5.Öğrenci, öğrenim görmüş olduğu tüm dönemlerde almış olduğu derslerin genel not
bilgilerine; dönem akademik ortalaması ve genel akademik ortalama bilgilerine
ulaşır.Öğrenciye; kişisel bilgileri, öğrenim gördüğü tüm dönemlerde aldığı derslerin not
dökümleri, dönemler birbirinden belirgin bir şekilde ayrılarak yansıtılır.Bu not dökümü; ilgili
döneme ait tüm derslerin ders kodu, ders adı, kredi bilgileri, genel ve/veya bütünleme notu
bilgilerini içerir.Tüm dönemlere ait dönem akademik ortalama bilgisine ek olarak, öğrencinin
genel akademik ortalaması her dönemden sonra ayrı ayrı hesaplanarak ekrana yansıtılır.
Eğer öğrenci herhangi bir dersi ileriki bir dönemde tekrar almışsa bu durum ilgili dönemde bir
ibare ile öğrenciye yansıtılır.
6.Öğrenci kendi hakkında olan tüm bilgileri görüntüleyebilir.Öğrenci Katalog izleme ekranında
Bölüm kodu ve Döküm yılı bilgilerini girmelidir.Bölüm kodu bilgisi Optik kodlar butonuna
basınca ulaşılan yeni ekrandan öğrenilir.Öğrenci Döküm yılına ulaşmak istediği yılı kodlaması
gerekmektedir. Bütün bu işlemlerden sonra tamam butonuna basınca Öğrenci istediği
kataloga erişir.
7.Öğrenci bulunduğu eğitim-öğretim döneminde alacağı dersleri seçmek/eklemek için sisteme
giriş yapar.Her öğrenci ders seçmek ve ders kaydını yapmak için belirtilen tarihlerde, bu giriş
ekranına ulaşır.Öğrenci, öğrenci numarası ve belirlediği şifresini girerek sisteme giriş yapar.
8.Öğrenci bulunduğu eğitim-öğretim döneminde alacağı dersleri seçmek/eklemek amacıyla
sistemi kullanır.Öğrenciler ders eklemek için belirtilen tarihlerde, başarılı bir şekilde giriş
yaptıkları takdirde bu ekrana ulaşırlar.Ders ekleme ekranında, derslerin optik kodlarının
girilmesi için 20 adet kutucuk bulunur ve bu kutucukların yanında o dersin şube seçimi
yapılması için şube kutucukları bulunur. Her öğrenci, ders seçmek/eklemek istediği dersin
optik kodunu ve şubesini ilgili kutucuklara yazar.Öğrenci istediği kadar dersin kodunu,
şubesini yazdıktan sonra “değişiklikleri kaydet” butonuna basarak derslerin sistemde kendi
üzerine eklenmesini sağlar.Ekranın üst kısmında, gerçekleşen eylemler bilgilendirilme amaçlı
yer alır.Eğer öğrencinin eklendiği dersler başarılı bir şekilde sistemde öğrenci üzerine
eklendiyse, ders ekleme işlemi başarılı uyarısı gelecektir.
Eğer öğrencinin eklediği dersler başarılı bir şekilde eklenmediyse, ders ekleme işlemi
başarısız diye bir uyarı gelecektir.Dersin kapasitesinin dolu olması, dersin ilgili dönemde
açılmamış olması gibi sebeplerle ders ekleme işlemi başarısız olabilir.Öğrenci eklemiş olduğu
dersin, şubesini değiştirebilir, bunun için şube kutucuğuna yeni şubesini yazıp, “değişiklikleri
kaydet” butonuna basar.Şube değişikliği başarılı olursa, şube değişikliği başarılı diye mesaj
görüntülenir.Eğer başarısız olursa, şube değişimi başarısız uyarısı görüntülenir.
Öğrenci seçmiş olduğu dersi silebilir. Bunun için dersin yanında bulunan “sil” kutucuğunu
işaretleyip, “değişiklikleri kaydet” butonuna tıklaması yeterlidir.
9.Danışman bulunduğu eğitim-öğretim döneminde, öğrencilerin seçtiği dersleri denetleyerek,
öğrencilerin ders kayıtlarını onaylamak amacıyla sisteme giriş yapar.Her danışman ders
kaydını onaylamak için belirtilen tarihlerde, bu giriş ekranına ulaşır.Danışman, kullanıcı
numarasını ve belirlediği şifresini girerek sisteme giriş yapar.
10.Danışman o eğitim öğretim döneminde danışmanı olduğu öğrencinin ders seçimlerini
inceler ve onaylar.Akademik personel danışmanı olduğu öğrenciler listesinden seçim yapar ve
öğrencinin bilgilerinin ve yaptığı ders seçimlerinin bulunduğu ekrana ulaşır.Öğrencinin seçmiş
olduğu dersleri inceleyerek “Onayla” butonuna tıklayarak ders kaydını onaylamış olur.
11.Danışman o eğitim öğretim döneminde danışmanı olduğu öğrencinin ders seçimlerinde
ekleme ve silme yapabilir.Akademik personel danışmanı olduğu öğrenciler listesinden seçim
yapar ve öğrencinin bilgilerinin ve yaptığı ders seçimlerinin bulunduğu ekrana ulaşır.Her
dersin yanında kutucuklar bulunur ve silinmesi gereken ders varsa bu kutu işaretlenir.Ders
listesinin altında kutucuk bulunur ve eklenmesi gereken ders varsa buraya yazılır.Danışman
‘Kaydet’ tuşuna basarak yaptığı değişiklikler varsa kaydeder.
12.Akademik döneme ait önemli tarihler akademik takvim üzerinden öğrenilir.Ders kayıt
haftası sınav dönemleri, resmi tatiller gibi önemli gün ve tarihler belirlenir.Belirlenen tarihlere
göre bir takvim oluşturulur.Takvim sisteme yüklendikten sonra kullanıcının ulaşabileceği
bağlantı linki verilir.Kullanıcı linke tıklayarak erişim sağlar.
13.Şifreler ve güvenlik ekranı şifre işlemlerinin düzenlenmesini sağlar. Kullanıcı tarafından
şifremi unuttum kısmına gidilir.Ekrana gelen form aracılığıyla şifre güncelleme için istek
yapılır.Kullanıcı forma geçerli bir mail adresi girer.Verilen maile yeni şifre belirlemek için
sistem tarafından link yollanır.Kullanıcı linke tıklayarak şifre güncellemesi yapılan ekrana
ulaşır.Bu ekran üzerinde ayrılmış alanda yeni şifresini oluşturur.Şifre doğrulama kontrolü
yapılır.Doğrulama sonucu başarılı olduğunda ekrana işlem başarılı mesajı verilerek işlem
tamamlanır.İşlem bittikten sonra ilgili ekrandan çıkış yapılır.
14.Akademik Personel sicil numarası ve şifre ile sisteme giriş yapar.Akademik Personel
kendisine verilen sicil numarası ve şifreyi kullanarak login ekranından giriş yapar.
15.Akademik Personel o eğitim öğretim döneminde verdiği dersler alan öğrencilerin notlarını
girer.Üzerine ders kayıtlı her öğretim elemanı, belirtilen tarihlerde not giriş işlemlerini
yapabileceği bu ekrana ulaşır.Başarılı bir şekilde giriş yaptığı takdirde üzerine kayıtlı derslerin
göründüğü bir ekranla karşılaşır.Her ders için bağlantıya tıkladığında, o derse kayıtlı
öğrencilerin olduğu liste gelir. Bu listede öğrencilerin isimleri, numaraları yer alır.Her öğrenci
numarasının yanında not kutucukları vardır.Her öğrenciye not girişi bu kutucuklardan biri
işaretlenerek yapılır.Görevli not girişi yaptıktan sonra “kaydet” tuşuna basarak, notların
sisteme kaydedilmesini sağlar.
16.Öğrenci İşleri Personeli önceden kendisine tanımlanan yetkiyle sistemi kullanabilir.
Personel, sicil numarası ve şifre ile sisteme giriş yapar.
17.Öğrenci İşleri Personeli önceden kendisine tanımlanan yetkiyle sistemi kullanabilir.
Öğrenci numarasını girerek ilgili öğrencinin bilgilerine erişir.Güncelleme yapılacak alanı
doldurur.Kaydet butonuna basarak işlemi sonlandırır.
