### ISSUE TITLE
Kullanıcı Ara Yüzü Tasarlama

### ISSUE THREAD

**Issue by SemihAdiguzel** [SemihAdiguzel/BBM487-20142-9#4]
Sistemin kullanıcı arayüzlerini tasarlayınız.

**Comment by ErenErenay** [comment]
![kisisel-bilgiler](https://cloud.githubusercontent.com/assets/11216235/6651555/42cda300-ca50-11e4-968e-651c89a14a9f.png)
![sifre](https://cloud.githubusercontent.com/assets/11216235/6651556/42d0bc84-ca50-11e4-9591-d42b46f4ec90.png)
![2014bahar](https://cloud.githubusercontent.com/assets/11216235/6651557/42d54c40-ca50-11e4-9e0d-6d88db955fb1.png)
![anasayfa](https://cloud.githubusercontent.com/assets/11216235/6651558/42d76232-ca50-11e4-933b-e03f66e3cfae.png)
![bilgi-gunclle](https://cloud.githubusercontent.com/assets/11216235/6651559/42dabc84-ca50-11e4-8099-589948956716.png)
![giris-sistmi](https://cloud.githubusercontent.com/assets/11216235/6651560/42dd8090-ca50-11e4-9704-47c8c9553fe9.png)
![karne](https://cloud.githubusercontent.com/assets/11216235/6651561/42ec7154-ca50-11e4-8d60-6f3c9acda51a.png)
